In [1]:
import pandas as pd
import numpy as np
import requests
from io import StringIO
from bs4 import BeautifulSoup

In [2]:
inicio=10
valores=[]
while inicio != 24:
    
    fin=inicio+1
    valores.append(str(inicio)+str(fin))
    inicio +=1

In [3]:
valores

['1011',
 '1112',
 '1213',
 '1314',
 '1415',
 '1516',
 '1617',
 '1718',
 '1819',
 '1920',
 '2021',
 '2122',
 '2223',
 '2324']

In [4]:
def renombrarColumnas(tabla,columna1="HomeTeam",columna2="AwayTeam"):
    tabla[columna1] = tabla[columna1].replace({
        'Hercules': 'ID031',
        'Levante': 'ID024',
        'Malaga': 'ID029',
        'Espanol': 'ID021',
        'La Coruna': 'ID028',
        'Mallorca': 'ID015',
        'Osasuna': 'ID012',
        'Santander': 'ID032',
        'Sociedad': 'ID006',
        'Ath Madrid': 'ID003',
        'Ath Bilbao': 'ID004',
        'Barcelona': 'ID005',
        'Real Madrid': 'ID002',
        'Valencia': 'ID008',
        'Getafe': 'ID010',
        'Sevilla': 'ID016',
        'Sp Gijon': 'ID030',
        'Villarreal': 'ID014',
        'Zaragoza': 'ID033',
        'Almeria': 'ID020',
        'Granada': 'ID019',
        'Betis': 'ID007',
        'Vallecano': 'ID013',
        'Celta': 'ID017',
        'Valladolid': 'ID022',
        'Elche': 'ID023',
        'Eibar': 'ID025',
        'Cordoba': 'ID034',
        'Las Palmas': 'ID009',
        'Leganes': 'ID027',
        'Alaves': 'ID011',
        'Girona': 'ID001',
        'Huesca': 'ID026',
        'Cadiz': 'ID018'
    })
    
    tabla[columna2] = tabla[columna2].replace({
        'Hercules': 'ID031',
        'Levante': 'ID024',
        'Malaga': 'ID029',
        'Espanol': 'ID021',
        'La Coruna': 'ID028',
        'Mallorca': 'ID015',
        'Osasuna': 'ID012',
        'Santander': 'ID032',
        'Sociedad': 'ID006',
        'Ath Madrid': 'ID003',
        'Ath Bilbao': 'ID004',
        'Barcelona': 'ID005',
        'Real Madrid': 'ID002',
        'Valencia': 'ID008',
        'Getafe': 'ID010',
        'Sevilla': 'ID016',
        'Sp Gijon': 'ID030',
        'Villarreal': 'ID014',
        'Zaragoza': 'ID033',
        'Almeria': 'ID020',
        'Granada': 'ID019',
        'Betis': 'ID007',
        'Vallecano': 'ID013',
        'Celta': 'ID017',
        'Valladolid': 'ID022',
        'Elche': 'ID023',
        'Eibar': 'ID025',
        'Cordoba': 'ID034',
        'Las Palmas': 'ID009',
        'Leganes': 'ID027',
        'Alaves': 'ID011',
        'Girona': 'ID001',
        'Huesca': 'ID026',
        'Cadiz': 'ID018'
    })
    return tabla

In [5]:
def rename_column(pd_series):
    pd_series = pd_series.replace({
        'F.C. Barcelona': 'ID005',
        'Real Madrid C.F.':'ID002',
        'Valencia C.F.': 'ID008',
        'Atlético de Madrid': 'ID003',
        'Sevilla F.C.': 'ID016',
        'Villarreal C.F.': 'ID014',
        'R.C. Deportivo': 'ID028', 
        'Getafe C.F.': 'ID010', 
        'R.C.D. Espanyol': 'ID021',
        'Real Racing Club': 'ID032', 
        'Athletic Club de Bilbao': 'ID004', 
        'U.D. Almería': 'ID020',
        'Málaga C.F.': 'ID029', 
        'Real Valladolid C.F.': 'ID022', 
        'Real Zaragoza': 'ID033',
        'Club Atlético Osasuna': 'ID012', 
        'R.C.D. Mallorca': 'ID015',
        'Real Sporting de Gijón': 'ID030', 
        'C.D. Tenerife': 'ID035', 
        'Xerez C.D.':'ID036',
        'Real Madrid  ': 'ID002', 
        'Club Atlético de Madrid  ': 'ID003',
        'Sevilla Fútbol Club  ': 'ID016', 
        'Valencia    ': 'ID008', 
        'Villarreal    ': 'ID014',
        'Getafe    ': 'ID010', 
        'Real Club Deportivo de La Coruña  ':'ID028',
        'R.C.D. Espanyol de Barcelona  ': 'ID021', 
        'Real Sporting de Gijón  ': 'ID030',
        'Real Zaragoza  ': 'ID033', 
        'Real Club Deportivo Mallorca  ': 'ID015',
        'Unión Deportiva Almería  ': 'ID020', 
        'Real Racing Club  ': 'ID032', 
        'Hércules    ':'ID031',
        'Málaga    ': 'ID029',
        'Real Sociedad de Fútbol  ':'ID006',
        'Levante Unión Deportiva  ':'ID024',
        'Real Betis Balompié  ':'ID007',
        'Granada  ':'ID019',
        'Rayo Vallecano de Madrid  ':'ID013', 
        'FC Barcelona':'ID005',
        'Club Atlético de Madrid':'ID003',
        'Valencia  ':'ID008',
        'Málaga  ': 'ID029',
        'Sevilla Fútbol Club':'ID016',
        'Real Sociedad de Fútbol': 'ID006',
        'Real Betis Balompié': 'ID007',
        'Getafe  ':'ID010', 
        'RCD Espanyol de Barcelona': 'ID021',
        'Levante Unión Deportiva':'ID024',
        'Rayo Vallecano de Madrid':'ID013',
        'Real Valladolid  ':'ID022', 
        'Real Club Deportivo de La Coruña':'ID028',
        'Real Club Deportivo Mallorca':'ID015',
        'Real Club Celta de Vigo':'ID017',
        'Elche  ':'ID023', 
        'Unión Deportiva Almería':'ID020', 
        'Villarreal  ':'ID014', 
        'SD Eibar':'ID025',
        'Córdoba  ':'ID034',
        'Real Madrid CF':'ID002',
        'Atlético Madrid': 'ID003', 
        'Valencia CF': 'ID008',
        'Sevilla FC': 'ID016',
        'Villarreal CF': 'ID014',
        'Real Sociedad': 'ID006', 
        'RC Celta de Vigo':'ID017',
        'Málaga CF': 'ID029',
        'RC Deportivo de La Coruña':'ID028',
        'RCD Espanyol':'ID021',
        'Levante UD':'ID024',
        'Rayo Vallecano':'ID013',
        'Getafe CF':'ID010', 
        'Granada CF':'ID019',
        'UD Las Palmas':'ID009', 
        'CD Leganés':'ID027',
        'Deportivo Alavés':'ID011', 
        'CA Osasuna':'ID012',
        'Girona CF':'ID001', 
        'Real Madrid':'ID002', 
        'Real Betis':'ID007', 
        'Athletic Club':'ID004',
        'RC Celta':'ID017',
        'Girona FC':'ID001', 
        'D. Alavés':'ID011',
        'R. Valladolid CF':'ID022',
        'SD Huesca':'ID026',
        'RCD Mallorca':'ID015',
        'Cádiz CF':'ID018', 
        'Elche CF':'ID023', 
        'UD Almería':'ID020'})
    return pd_series

### General Statistics

In [6]:
def filtrarColumnas(data):
    if "Time" in data.columns:
        data = data.drop(["Time"], axis=1)
    data = data.drop(data.columns[range(tabla.columns.get_loc("B365H"),data.shape[1])], axis=1)
    
    if "B365H" in data.columns:
        data = data.drop("B365H",axis=1)
    return data

In [7]:
def crearMatriz(data):
    tmp_matrix = np.full((20, 40), np.nan)
    columnas =  [f'Jornada_{i}' for i in range(1, 41)]
    filas = sorted(data['HomeTeam'].unique())
    tmp_matrix = pd.DataFrame(tmp_matrix, columns=columnas)
    filas = filas
    tmp_matrix.index = filas
    tmp_matrix
    return tmp_matrix, filas

In [8]:
def goalDiff(data,filas,goal_diff):
    for j in filas:
        t=1
        #for i in range(data.shape[0] - 1, -1, -1):
        for i in range(data.shape[0]):
            if j == data.iloc[i, 2]:
                tmp_diff = data.iloc[i, 4] - data.iloc[i, 5]
                if pd.isna(goal_diff.loc[j, 'Jornada_1']):
                    goal_diff.loc[j, 'Jornada_1'] = tmp_diff
                    t+=1
                else:
                    goal_diff.loc[j, f'Jornada_{t}'] = goal_diff.loc[j, f'Jornada_{t-1}'] + tmp_diff
                    t += 1  
            
            elif j == data.iloc[i, 3]:
                tmp_diff = data.iloc[i, 5] - data.iloc[i, 4]
                if pd.isna(goal_diff.loc[j, 'Jornada_1']):
                    goal_diff.loc[j, 'Jornada_1'] = tmp_diff
                    t+=1
                else:
                    goal_diff.loc[j, f'Jornada_{t}'] = goal_diff.loc[j, f'Jornada_{t-1}'] + tmp_diff
                    t += 1
    
    
    goal_diff = goal_diff / goal_diff.max().max()
    goal_diff.insert(loc=0,column="Jornada_0",value=0)
    return goal_diff, filas

In [9]:
def cornersDiff(data,filas,corns_diff):
    for j in filas:
        t=1
        #for i in range(data.shape[0] - 1, -1, -1):
        for i in range(data.shape[0]):
            if j == data.iloc[i, 2]:
                tmp_diff = data.iloc[i, 16] - data.iloc[i, 17]
                if pd.isna(corns_diff.loc[j, 'Jornada_1']):
                    corns_diff.loc[j, 'Jornada_1'] = tmp_diff
                    t+=1
                else:
                    corns_diff.loc[j, f'Jornada_{t}'] = corns_diff.loc[j, f'Jornada_{t-1}'] + tmp_diff
                    t += 1  

            elif j == data.iloc[i, 3]:
                tmp_diff = data.iloc[i, 17] - data.iloc[i, 16]
                if pd.isna(corns_diff.loc[j, 'Jornada_1']):
                    corns_diff.loc[j, 'Jornada_1'] = tmp_diff
                    t+=1
                else:
                    corns_diff.loc[j, f'Jornada_{t}'] = corns_diff.loc[j, f'Jornada_{t-1}'] + tmp_diff
                    t += 1
                    
    corns_diff= corns_diff/ corns_diff.max().max()
    corns_diff.insert(loc=0,column="Jornada_0",value=0)
    return corns_diff, filas

In [10]:
def shootsDiff(data,filas,shoots_diff):
    for j in filas:
        t=1
        #for i in range(data.shape[0] - 1, -1, -1):
        for i in range(data.shape[0]):
            if j == data.iloc[i, 2]:
                tmp_diff = data.iloc[i, 12] - data.iloc[i, 13]
                if pd.isna(shoots_diff.loc[j, 'Jornada_1']):
                    shoots_diff.loc[j, 'Jornada_1'] = tmp_diff
                    t+=1
                else:
                    shoots_diff.loc[j, f'Jornada_{t}'] = shoots_diff.loc[j, f'Jornada_{t-1}'] + tmp_diff
                    t += 1  

            elif j == data.iloc[i, 3]:
                tmp_diff = data.iloc[i, 13] - data.iloc[i, 12]
                if pd.isna(shoots_diff.loc[j, 'Jornada_1']):
                    shoots_diff.loc[j, 'Jornada_1'] = tmp_diff
                    t+=1
                else:
                    shoots_diff.loc[j, f'Jornada_{t}'] = shoots_diff.loc[j, f'Jornada_{t-1}'] + tmp_diff
                    t += 1
                    
    shoots_diff= shoots_diff/ shoots_diff.max().max()
    shoots_diff.insert(loc=0,column="Jornada_0",value=0)
    return shoots_diff, filas

In [11]:
def matrizVacia(data):
    cols = data.columns[[4, 5] + list(range(7, 22))]
    data=data.drop(cols,axis=1)
    data['HTCD'] = None
    data['ATCD'] = None
    data['HTGD'] = None
    data['ATGD'] = None
    data['HTSD'] = None
    data['ATSD'] = None
    data['HomeRating(ELO) 0.05'] = None
    data['AwayRating(ELO) 0.05'] = None
    data['HomeRating(ELO) 0.1'] = None
    data['AwayRating(ELO) 0.1'] = None
    data['HomeRating(ELO) 0.25'] = None
    data['AwayRating(ELO) 0.25'] = None
    data['HomeRating(ELO) 0.4'] = None
    data['AwayRating(ELO) 0.4'] = None
    data['HomeRating(ELO) 0.55'] = None
    data['AwayRating(ELO) 0.55'] = None
    data['HomeRating(ELO) 0.7'] = None
    data['AwayRating(ELO) 0.7'] = None
    data['HomeRating(ELO) 0.85'] = None
    data['AwayRating(ELO) 0.85'] = None
    data['HomeRating(ELO) 0.9'] = None
    data['AwayRating(ELO) 0.9'] = None
    data['Value Diff'] = None
    data['Attack Diff'] = None
    data['Mid Game Diff'] = None
    data['Defense Diff'] = None
    data['Over Game Diff'] = None
    return data

In [12]:
def resultadosCorner(data,filas,variable,resultados):
    for j in filas:
        t=0
        for i in range(data.shape[0]):
            if data.iloc[i,2] == j:
                resultados.loc[i,"HTCD"]=variable.loc[j,f'Jornada_{t}']
                t+=1
            elif data.iloc[i,3] == j:
                resultados.loc[i,"ATCD"]=variable.loc[j,f'Jornada_{t}']
                t+=1

    return resultados, filas

In [13]:
def resultadosShoots(data,filas,variable,resultados):
    for j in filas:
        t=0
        for i in range(data.shape[0]):
            if data.iloc[i,2] == j:
                resultados.loc[i,"HTSD"]=variable.loc[j,f'Jornada_{t}']
                t+=1
            elif data.iloc[i,3] == j:
                resultados.loc[i,"ATSD"]=variable.loc[j,f'Jornada_{t}']
                t+=1

    return resultados, filas

In [14]:
def resultadosGoles(data,filas,variable,resultados):
    for j in filas:
        t=0
        for i in range(data.shape[0]):
            if data.iloc[i,2] == j:
                resultados.loc[i,"HTGD"]=variable.loc[j,f'Jornada_{t}']
                t+=1
            elif data.iloc[i,3] == j:
                resultados.loc[i,"ATGD"]=variable.loc[j,f'Jornada_{t}']
                t+=1

    return resultados, filas

In [15]:
def ratingsMatrix(data):
    tmp_matrix = np.full((20, 40), np.nan)
    columnas =  [f"{i}" for i in range(1, 41)]
    filas = sorted(data['HomeTeam'].unique())
    tmp_matrix = pd.DataFrame(tmp_matrix, columns=columnas)
    filas = filas
    tmp_matrix.index = filas
    tmp_matrix.insert(loc=0,column="0",value=1)
    return tmp_matrix, filas

In [16]:
def ratingDiff(data,rating_diff,gamma):
    for i in range(data.shape[0]):
        id1=data.iloc[i,2]
        id2=data.iloc[i,3]
        posit1=rating_diff.loc[id1,:].last_valid_index()
        posit2=rating_diff.loc[id2,:].last_valid_index()

        next_posit1= rating_diff.columns.get_loc(str(int(posit1)+1))
        next_posit2= rating_diff.columns.get_loc(str(int(posit2)+1))

        mu_alfa = rating_diff.loc[id1,str(posit1)]
        mu_beta = rating_diff.loc[id2,str(posit2)]

        if data.iloc[i,6] == "H":
            mu_alfa = mu_alfa + gamma * mu_beta
            mu_beta = mu_beta - gamma * mu_alfa

        elif data.iloc[i,6] == "A":
            mu_alfa = mu_alfa - gamma * mu_beta
            mu_beta = mu_beta + gamma * mu_alfa

        else:
            mu_alfa = mu_alfa - gamma* (mu_alfa - mu_beta)
            mu_beta = mu_beta - gamma* (mu_beta - mu_alfa)

        rating_diff.loc[id1,str(next_posit1)] = mu_alfa
        rating_diff.loc[id2,str(next_posit2)] = mu_beta
        
    columnas =  [f"Jornada_{i}" for i in range(0, 41)]
    rating_diff.columns = columnas
        
    return rating_diff

In [17]:
def resultadosRating(data,filas,variable,resultados,colA,colH):
    for j in filas:
        t=0
        for i in range(data.shape[0]):
            if data.iloc[i,2] == j:
                resultados.loc[i,colH]=variable.loc[j,f'Jornada_{t}']
                t+=1
            elif data.iloc[i,3] == j:
                resultados.loc[i,colA]=variable.loc[j,f'Jornada_{t}']
                t+=1

    return resultados, filas

In [18]:
gammas = [0.05,0.1,0.25,0.4,0.55,0.7,0.85,0.9]

## **Team's Market Value**

In [19]:
def extract_club_values_table(soup):
    # Buscar la tabla en el objeto BeautifulSoup proporcionado
    table = soup.find('div', class_='responsive-table').find('table', class_='items')
    
    if table:
        # Convertir la tabla HTML a DataFrame de pandas
        df = pd.read_html(str(table))[0]
        df = df.iloc[:20,[1,6]]     
        return df

In [20]:
dfs = []

# Iterar a través de los años en el rango deseado
for i in range(10, 24):
    url = f'https://www.transfermarkt.com/laliga/startseite/wettbewerb/ES1/plus/?saison_id=20{i}'
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
    response = requests.get(url, headers=headers)
    
    if response.status_code == 200:
        soup = BeautifulSoup(response.text, 'html.parser')
        df = extract_club_values_table(soup)
        
        if df is not None:
            print(f"Tabla encontrada para el año 20{i}")
            dfs.append(df)# Agregar el dataframe a la lista de dataframe

dfs[1]

Tabla encontrada para el año 2010
Tabla encontrada para el año 2011
Tabla encontrada para el año 2012
Tabla encontrada para el año 2013
Tabla encontrada para el año 2014
Tabla encontrada para el año 2015
Tabla encontrada para el año 2016
Tabla encontrada para el año 2017
Tabla encontrada para el año 2018
Tabla encontrada para el año 2019
Tabla encontrada para el año 2020
Tabla encontrada para el año 2021
Tabla encontrada para el año 2022
Tabla encontrada para el año 2023

                    Club.1 ø market value
0             FC Barcelona       €618.20m
1              Real Madrid       €539.20m
2       Atlético de Madrid       €210.00m
3              Valencia CF       €181.00m
4          Athletic Bilbao       €144.20m
5            Villarreal CF       €137.00m
6               Sevilla FC       €133.00m
7                Málaga CF       €121.30m
8   RCD Espanyol Barcelona        €81.20m
9            Real Sociedad        €74.70m
10               Getafe CF        €70.95m
11            RCD Mallorca        €62.20m
12           Real Zaragoza        €61.00m
13              Granada CF        €60.60m
14          Sporting Gijón        €53.40m
15     Real Betis Balompié        €52.70m
16          Rayo Vallecano        €47.30m
17              CA Osasuna        €44.40m
18        Racing Santander        €42.60m
19              Levante UD        €40.25m

### **Formateado de los datos**

In [21]:
def convertir_valor_df(valor):
    if valor.endswith("bn"):
        numero = float(valor[1:-2]) * 1_000_000_000
    elif valor.endswith("m"):
        numero = float(valor[1:-1]) * 1_000_000
    else:
        numero = valor
    return f"{numero:.0f}"

In [22]:
for i in range(len(dfs)):
    
    dfs[i]["Club.1"]=dfs[i]["Club.1"].replace({
     'FC Barcelona': 'ID005',
     'Real Madrid': 'ID002',
     'Atlético de Madrid': 'ID003',
     'Valencia CF': 'ID008',
     'Sevilla FC':'ID016',
     'Villarreal CF':'ID014',
     'Athletic Bilbao': 'ID004',
     'RCD Espanyol Barcelona': 'ID021',
     'UD Almería':'ID020',
     'Málaga CF':'ID029',
     'Real Sociedad':'ID006',
     'Getafe CF':'ID010',
     'Deportivo de La Coruña':'ID028',
     'Racing Santander': 'ID032',
     'CA Osasuna':'ID012',
     'Real Zaragoza':'ID033',
     'RCD Mallorca':'ID015',
     'Sporting Gijón':'ID030',
     'Hércules CF':'ID031',
     'Levante UD':'ID024',
     'Granada CF':'ID019',
     'Real Betis Balompié':'ID007',
     'Rayo Vallecano':'ID013',
     'Celta de Vigo':'ID017',
     'Real Valladolid CF':'ID022',
     'Elche CF':'ID023',
     'Córdoba CF':'ID034',
     'SD Eibar':'ID025',
     'UD Las Palmas':'ID009',
     'Deportivo Alavés':'ID011',
     'CD Leganés':'ID027',
     'Girona FC':'ID001',
     'SD Huesca':'ID026',
     'Cádiz CF':'ID018'
    })
    dfs[i].columns = ["Club","Value"]
    dfs[i]["Value"] = dfs[i]["Value"].apply(convertir_valor_df)
    dfs[i]["Value"] = pd.to_numeric(dfs[i]["Value"])

In [23]:
lista=[11,"12_8","13_11","14_12",15,16,17,18,19,20,21,22,23,24]

In [24]:
fifa_statistics=[]
for i in lista:
    url = f"https://www.fifaindex.com/teams/fifa{i}/?league=53&order=desc"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    table = soup.find("table", class_="table-teams")
    
    # Extraer los encabezados de las columnas
    headers = [header.text.strip() for header in table.find_all("th")]
    
    # Extraer las filas de la tabla
    rows = []
    for row in table.find_all("tr")[1:]:  # Excluyendo el encabezado
        columns = row.find_all("td")
        if columns:
            rows.append([col.text.strip() for col in columns])
    
    # Crear el DataFrame de Pandas
    df = pd.DataFrame(rows, columns=headers)
    df= df.dropna()
    df = df.drop("League",axis=1)
    df["Name"] = df["Name"].str.replace("S.A.D."," ")
    df["Name"] = df["Name"].str.replace("Club de Fútbol"," ")
    df["Name"] = rename_column(df["Name"])
    
    fifa_statistics.append(df)

## **Obtención de estadísticas en la tabla final**

In [336]:
final_results=pd.DataFrame()
year=0
for i in valores:
    #Obtener la tabla con la que vamos a trabajar:
    url = "https://www.football-data.co.uk/mmz4281/"+f"{i}"+"/SP1.csv"
    s = requests.get(url).content.decode('utf-8') 
    data=StringIO(s)
    tabla = pd.read_csv(data)
    
    #renombramos los nombres en "HomeTeam" "AwayTeam" por sus identificadores
    tabla = renombrarColumnas(tabla)
    tabla = filtrarColumnas(tabla)
    
    #Creamos las matrices temporales para las diferentes variables
    tmp_goal_diff, filas  = crearMatriz(tabla)
    tmp_corns_diff, filas = crearMatriz(tabla)
    tmp_shoots_diff, filas = crearMatriz(tabla)
    
    #Diferencia de goles
    goal_diff, filas =goalDiff(tabla,filas,tmp_goal_diff)
    corns_diff, filas = cornersDiff(tabla,filas,tmp_corns_diff)
    shoots_diff, filas = shootsDiff(tabla,filas,tmp_shoots_diff)

    #Generamos la matriz de resultados
    resultados=matrizVacia(tabla)
    
    #Añadimos los resultados a las columnas de corners
    resultados, filas= resultadosCorner(tabla,filas,corns_diff,resultados)
    resultados, filas= resultadosShoots(tabla,filas,shoots_diff,resultados)
    resultados, filas = resultadosGoles(tabla,filas,goal_diff, resultados)
    
    #Crear matrix de ratings (Sistema ELO)
    for gamma in gammas:
        rating_diff, filas =ratingsMatrix(tabla)
        rating_diff = ratingDiff(tabla,rating_diff,gamma=gamma)
        colA=f'AwayRating(ELO) {gamma}'
        colH=f'HomeRating(ELO) {gamma}'
        
        resultados, filas = resultadosRating(tabla,filas,rating_diff,resultados,colA,colH)

    for t in range(resultados.shape[0]):
        for j in range(dfs[1].shape[0]):
            clubH = resultados.iloc[t,2]
            clubA = resultados.iloc[t,3]
            valorH= dfs[year].loc[dfs[year]["Club"] == clubH,"Value"].item()
            valorA= dfs[year].loc[dfs[year]["Club"] == clubA,"Value"].item()
            resultados.iloc[t,27] = valorH - valorA

    for t in range(resultados.shape[0]):
        for j in range(fifa_statistics[1].shape[0]):
            clubH = resultados.iloc[t,2]
            clubA = resultados.iloc[t,3]
            attH= fifa_statistics[year].loc[fifa_statistics[year]["Name"] == clubH,"ATT"].item()
            attA= fifa_statistics[year].loc[fifa_statistics[year]["Name"] == clubA,"ATT"].item()
            midH= fifa_statistics[year].loc[fifa_statistics[year]["Name"] == clubH,"MID"].item()
            midA= fifa_statistics[year].loc[fifa_statistics[year]["Name"] == clubA,"MID"].item()
            defH= fifa_statistics[year].loc[fifa_statistics[year]["Name"] == clubH,"DEF"].item()
            defA= fifa_statistics[year].loc[fifa_statistics[year]["Name"] == clubA,"DEF"].item()
            ovrH= fifa_statistics[year].loc[fifa_statistics[year]["Name"] == clubH,"OVR"].item()
            ovrA= fifa_statistics[year].loc[fifa_statistics[year]["Name"] == clubA,"OVR"].item()
            resultados.iloc[t,28] = int(attH) - int(attA)
            resultados.iloc[t,29] = int(midH) - int(midA)
            resultados.iloc[t,30] = int(defH) - int(defA)
            resultados.iloc[t,31] = int(ovrH) - int(ovrA)

    year +=1
    final_results= pd.concat([final_results,resultados])
    print(f"Fin de la iteracion: {year}")
final_results.iloc[:3040, 1] = final_results.iloc[:3040, 1].str[:6] + "20" + final_results.iloc[:3040, 1].str[6:]
#final_results.iloc[3040:, 1] = pd.to_datetime(final_results.iloc[3040:, 1], format='%d/%m/%Y')
#final_results['Date'] = pd.to_datetime(final_results['Date'], infer_datetime_format=True)

Fin de la iteracion: 1
Fin de la iteracion: 2
Fin de la iteracion: 3
Fin de la iteracion: 4
Fin de la iteracion: 5
Fin de la iteracion: 6
Fin de la iteracion: 7
Fin de la iteracion: 8
Fin de la iteracion: 9
Fin de la iteracion: 10
Fin de la iteracion: 11
Fin de la iteracion: 12
Fin de la iteracion: 13
Fin de la iteracion: 14

ValueError: Must have equal len keys and value when setting with an iterable

In [117]:
pd.set_option('display.max_rows', 100)  
pd.set_option('display.max_columns', 100)

Tras comprobar manualmente los resultados desde la página web, se verifica la veracidad de los resultadoss

#### **Extracción Nombre Árbitro del partido**

In [346]:
def extraer_html(url):
    url = str(url)
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, 'html.parser')
    return soup

In [347]:
%run Identificadores.ipynb
referees=[]
for i in range(10,24):
    url = f'https://www.bdfutbol.com/es/t/t20{i}-{i+1}.html?tab=results&jornada=-'
    soup=extraer_html(url)
    tables = soup.find_all("table")
    def find_matching_table(tables):
        for table in tables:
            headers = [header.get_text(strip=True) for header in table.find_all("th")]
            # Criterios de búsqueda simplificados para el ejemplo
            if "Fecha" in headers and "Local" in headers and "Visitante" in headers and "Árbitro" in headers:
                return table
        return None
    
    # Encontrar la tabla
    matching_table = find_matching_table(tables)
    
    # Extraeremos los datos de la tabla coincidente si se encontró una
    if matching_table:
        rows = matching_table.find_all("tr")
        table_data = []
        headers = [header.get_text(strip=True) for header in rows[0].find_all("th")]
    
        for row in rows[1:]:  # Saltar la fila de encabezados
            cols = row.find_all(["td", "th"])
            cols = [ele.text.strip() for ele in cols]
            table_data.append(cols)
        
        result = {
            "headers": headers,
            "data": table_data
        }
    
    lista =list(result.values())[1][1:]
    lista_filtrada = [sublista for sublista in lista if len(sublista) > 1]
    data =  pd.DataFrame(lista_filtrada, columns=['Date', 'HomeTeam','Resultado','AwayTeam','Estadio' ,'Arbitro'])
    data.replace('',pd.NA,inplace=True)
    data.dropna(inplace=True)
    data["HomeTeam"]= rename_column_bdfutbol_ref(data["HomeTeam"])
    data["AwayTeam"]= rename_column_bdfutbol_ref(data["AwayTeam"])
    #data['Date'] = pd.to_datetime(data['Date'], format='%d/%m/%Y')
    referees.append(data)

referees_df = pd.concat(referees)

In [274]:
#referees_df['Date'] = referees_df['Date'].dt.strftime('%d/%m/%Y')

#### **Extracción Identificadores de los respectivos árbitros**

In [348]:
referees_id =[]
for i in range(10,24):
    url = f'https://www.bdfutbol.com/es/t/t20{i}-{i+1}.html?tab=referees'
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, 'html.parser')
    
    links = soup.find_all('a', href=True)
    
    # Extrayendo los parámetros y nombres de los árbitros
    data = []
    for link in links:
        href = link.get('href')
        if 'r/r' in href:
            # Extrayendo el parámetro numérico del enlace
            param = href.split('/')[-1].replace('.html', '')
            # Extrayendo el nombre del árbitro
            name = link.text.strip()
            data.append({'Parametro': param, 'Arbitro': name})
    
    # Creando un DataFrame de pandas con los datos recopilados
    df = pd.DataFrame(data)
    referees_id.append(df)

referees_id = pd.concat(referees_id)
referees_id = referees_id[referees_id["Parametro"].apply(len) >3].drop_duplicates()

In [349]:
referees_id

   Parametro               Arbitro
4    r600000         Rubinos Pérez
5    r600001            Pérez Lasa
6    r600002       Muñiz Fernández
7    r600003     Teixeira Vitienes
8    r600004            Ayza Gámez
9    r600005    Fernández Borbalán
10   r600006     Álvarez Izquierdo
11   r600007      Delgado Ferreiro
12   r600008     González González
13   r600009     Ramírez Domínguez
14   r600011      Undiano Mallenco
15   r600012      Velasco Carballo
16   r600013        Paradas Romero
17   r600019     Teixeira Vitienes
18   r600010     Estrada Fernández
19   r600014           Mateu Lahoz
20   r600015      Turienzo Álvarez
21   r600016            Clos Gómez
22   r600017    Iturralde González
23   r600018   Iglesias Villanueva
9    r600410         Pérez Montero
18   r600409      Del Cerro Grande
13   r600428   Hernández Hernández
17   r600422           Gil Manzano
4    r600423      Martínez Munuera
22   r600420       Prieto Iglesias
6    r600495       Bikandi Garrido
9    r600412          Melero López
14   r600424           Jaime Latre
11   r600494  De Burgos Bengoetxea
15   r600497      Sánchez Martínez
12   r600709       Munuera Montero
20   r600414           Ocón Arraiz
32   r600419       Trujillo Suárez
13   r600586         Medié Jiménez
17   r600987        Alberola Rojas
20   r600587      González Fuertes
4    r600992      Cuadra Fernández
13   r600694          Cordero Vega
10   r600751            Soto Grado
21   r600729         Pizarro Gómez
6    r601073          Díaz de Mera
16   r600584      Figueroa Vázquez
5    r600775           Ortiz Arias
15   r601069            Muñiz Ruiz
11   r600675   Iglesias Villanueva
15   r600727        Pulido Santana
6    r600734       Hernández Maeso
7    r601363        García Verdura
40   r601413       Busquets Ferrer

In [350]:
referees = pd.merge(referees_df,referees_id, on ="Arbitro")

In [280]:
#referees = referees.sort_values(by="Date")

#### **Extracción estadísticas del árbitro**

In [351]:
ref_ids=list(referees_id["Parametro"].unique())

In [352]:
ref_stats = pd.DataFrame(data= None)
for i in ref_ids:
    url = f'https://www.bdfutbol.com/es/r/{i}.html?p=stats'
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, 'html.parser')
    
    tables = soup.find_all('table')
    target_table = None
    for table in tables:
        if "Expulsiones Por Partido" in table.text and "Tarjetas Amarillas Por Partido" in table.text:
            target_table = table
            break
    
    # Si se encontró la tabla, convertirla en un DataFrame
    if target_table:
        df = pd.read_html(str(target_table))[0]  # pd.read_html devuelve una lista de DataFrames
        df = df.iloc[[1, 2, 3,4, 7,8], [1]]  # Selecciona solo las filas y columnas deseadas
        df.index = [1, 2, 3,4, 7,8]  # Actualiza el índice para coincidir con ref_stats
        df.columns = [i]  # Renombra la columna con el id del árbitro
    else:
        df = pd.DataFrame(index=[1, 2, 3, 6, 7], columns=[i])  # Crea un DataFrame vacío con el índice correcto si no se encuentra la tabla
    
    ref_stats = pd.concat([ref_stats, df], axis=1)  # Concatena horizontalmente

In [353]:
ref_stats = ref_stats.T

In [354]:
ref_stats.rename(columns={1:"Partidos",2:"HomeWin",3:"AwayWin",4:"Empates",7:"Yellow Card/Match",8:"Red Card/Match"},inplace=True)

In [355]:
for column in ref_stats.columns:
    ref_stats[column] = ref_stats[column].str.replace(r'\s*\([^)]*\)', '', regex=True)

In [356]:
ref_stats

        Partidos HomeWin AwayWin Empates Yellow Card/Match Red Card/Match
r600000      149      69      46      34               5,5           0,47
r600001      276     138      76      62              5,77           0,38
r600002      252     121      65      66              5,98           0,42
r600003       95      42      31      22              6,53           0,39
r600004      157      70      53      34              4,79           0,38
r600005      244     107      74      63              5,39           0,32
r600006      222     119      51      52              5,73           0,38
r600007      131      51      46      34               5,1           0,23
r600008      221     106      65      50              4,74           0,22
r600009      184      92      46      46              5,14           0,34
r600011      348     148     104      96              4,99           0,22
r600012      217     117      46      54              6,19           0,48
r600013       86      49      16      21              5,85           0,43
r600019      226      97      67      62              5,29           0,35
r600010      240     116      63      61              5,54           0,27
r600014      287     135      84      68              4,88           0,23
r600015      220     117      63      40              5,65           0,35
r600016      215     100      69      46              5,34           0,41
r600017      291     144      76      71              5,46           0,41
r600018      176      87      41      48              5,52           0,32
r600410       89      33      33      23              5,39           0,25
r600409      236     102      71      63              5,04           0,26
r600428      218      93      59      66              5,72           0,33
r600422      230     103      65      62              5,45           0,26
r600423      199      97      58      44              4,68           0,18
r600420       96      46      26      24              4,66           0,17
r600495       59      33      17       9              3,58           0,34
r600412      171      81      47      43              5,14           0,16
r600424      154      75      35      44              5,22           0,23
r600494      171      81      55      35              4,78           0,19
r600497      175      82      54      39              5,57           0,25
r600709      148      64      53      31              4,62           0,28
r600414       17       8       7       2              4,59           0,18
r600419       36      16      10      10              5,08           0,28
r600586       70      32      19      19              4,99            0,3
r600987      126      55      33      38              3,54           0,15
r600587      133      60      39      34              5,23           0,28
r600992      106      49      36      21              4,89           0,32
r600694       75      33      16      26               4,8           0,21
r600751       98      55      17      26              5,33           0,16
r600729       70      30      16      24              4,16           0,31
r601073       70      22      23      25              5,43           0,33
r600584       72      33      19      20               4,4           0,32
r600775       50      21      15      14              4,32           0,48
r601069       52      28      10      14               5,5           0,33
r600675       35      16      11       8              4,54           0,17
r600727       36      23       6       7              5,19           0,25
r600734       14       8       3       3              5,21            007
r601363       14       5       1       8              4,29           0,29
r601413       15       6       1       8              5,67            0,4

In [357]:
ref_stats["% HomeWin"] = ref_stats["HomeWin"].astype("int") /  ref_stats["Partidos"].astype("int")
ref_stats["% AwayWin"] = ref_stats["AwayWin"].astype("int") /  ref_stats["Partidos"].astype("int")
ref_stats["% DrawWin"] = ref_stats["Empates"].astype("int") /  ref_stats["Partidos"].astype("int")

In [358]:
ref_stats = ref_stats.reset_index()

In [359]:
ref_stats.rename(columns={"index":"Parametro"},inplace=True)

In [360]:
final_referees = pd.merge(referees,ref_stats,on="Parametro")

In [361]:
final_refs = final_referees.loc[:,["Date","HomeTeam","AwayTeam","Estadio","Arbitro","Parametro","Yellow Card/Match","Red Card/Match","% HomeWin","% AwayWin","% DrawWin"]]

In [365]:
LaLiga = pd.merge(final_results, final_refs, on=["Date", "HomeTeam", "AwayTeam"], how="outer", indicator=True)

In [368]:
LaLiga = LaLiga[LaLiga["_merge"] == "both"]

In [369]:
LaLiga.to_csv("./LaLiga.csv")